Fix release pipeline
Need to use a later version of Ruby where `gem` command supports the
`exec` subcommand. Otherwise publishing the gem fails with:

```
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command exec
```